## Add these flags onto all target builds cumulatively.
## <https://github.com/rust-lang/cargo/issues/5376#issuecomment-2163350032>
[target.'cfg(all())']
rustflags = ["--cfg", "ruma_identifiers_storage=\"Arc\""]

## LiveKit/libwebrtc requires -ObjC linker flag on macOS
[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-Wl,-ObjC"]

[target.x86_64-pc-windows-msvc]                                                                                                                 
rustflags = ["-C", "target-feature=-crt-static"]                                                                                                
                                                                                                                                                
[target.aarch64-pc-windows-msvc]                                                                                                                
rustflags = ["-C", "target-feature=-crt-static"]